### PR TITLE
update version of comment-patterns dependency

### PR DESCRIPTION
**Pull request by seancsnyder**
This will now use the updated version of the comment-patterns repo.

### CODE REVIEW

**Comment by seancsnyder** [comment]
Sorry, one more change needed to ultimately use the php multi-line comments.

**Comment by seancsnyder** [comment]
👋

**Comment by seancsnyder** [comment]
I still need an approval on this one

**Comment by nknapp** [comment]
sorry for the delay. I have my mind full with other stuff. I added you as collaborator... will add you at npm as well

**Comment by seancsnyder** [comment]
No worries! Thanks for merging!!!

**Comment by nknapp** [comment]
It still needs to be published, maybe you can try that.

**Comment by seancsnyder** [comment]
Looks published to me. Did you take care of it?

**Comment by nknapp** [comment]
No, and [npmjs.com](https://www.npmjs.com/package/multilang-extract-comments) states that the last publish was 2 years ago.

**Comment by seancsnyder** [comment]
Ah I see that...but does have the correct version displayed 0.3.0....so
maybe it will resolve itself?

**Comment by nknapp** [comment]
Ah, no. `0.3.0` is still  the old version. If you want to publish, you have to increase it.

```
npm version minor
npm publish
git push --tags 
```

should do the trick.

**Comment by seancsnyder** [comment]
Got it! Thanks!

**Pull request merged**
